print("Pooj")
print("Pooj")
print("VVVPooj")
sal = "LLLPPPOOO"
print(sal[2:5])
print(f"Final value for sal variable is {sal}")
print("\n")
print("\n")
print(f"Functional varibale --> {sal}")
print(4/2)
print(4%2)
print(4+2)
print(4-2)
print(4**2)
print(4//2)